agenda/urls.py
from django.contrib import admin
from django.urls import path
from agenda.views import *

app_name = 'agenda'

urlpatterns = [
    path('tarefa/cadastro/', cadastro_tarefa, name = 'cadastro-tarefa'),
    path('tarefa/<int:id_tarefa>/alteracao/', alteracao_tarefa, name = 'alteracao-tarefa'),
    path('categoria/cadastro/', cadastro_categoria, name = 'cadastro-categoria'),
    path('tag/cadastro/', cadastro_tag, name = 'cadastro-tag'),
    path('cadastro/<int:id_tarefa>/descricao/', cadastro_descricao, name = 'cadastro-descricao'),
    path('cadastro/descricao/', cadastro_descricao, name = 'cadastro-descricao-form'),
    path('tarefa/<int:id_tarefa>/descricao/', descricao_tarefa, name = 'descricao'),
    path('tarefa/<int:id_tarefa>/deletar/', remover_tarefa, name = 'deletar'), # type: ignore
    path('tarefa/<int:id_tarefa>/concluida/', concluir_tarefa, name = 'concluir-tarefa'), # type: ignore
    path('ciclo/<int:id_ciclo>/descricao/', descricao_ciclo, name = 'descricao-ciclo'),
    path('ciclo/', home_ciclo, name = 'home-ciclo'),
    path('', home, name = 'home'),
]

financas/urls.py
from django.contrib import admin
from django.urls import path
from financas.views import *

app_name = 'financeiro'

urlpatterns = [
    path('', dashboad, name = 'dashboad'),
]

project/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('financas/', include('financas.urls')),
    path('', include('agenda.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

financas/models.py
from datetime import datetime, date
from typing import Any
from django.db import models
from django.utils import timezone


class Financeiro(models.Model):

    class Meta:

        verbose_name = 'Financeiro'

    saldo = models.FloatField(default = 0.0)

    cofrinho = models.FloatField(default = 0.0)

    def saque_saldo(self, valor:float) -> bool:

        if self.saldo - valor >= 0.0:

            self.saldo -= valor

            return True
    
        return False
    
    def deposito_saldo(self, valor:float):

        self.saldo += valor

    def saque_cofrinho(self, valor:float) -> bool:

        if self.cofrinho - valor >= 0.0:

            self.cofrinho -= valor

            return True
        
        return False
    
    def deposito_cofrinho(self, valor:float):

        self.cofrinho += valor



class Categoria(models.Model):

    class Meta:

        verbose_name = 'Categoria'

        verbose_name_plural = 'Categorias'

    nome = models.CharField(max_length = 100)

    def __str__(self) -> str:
        return self.nome



class Locais(models.Model):

    class Meta:

        verbose_name = 'Local'

        verbose_name_plural = 'Locais'

    nome = models.CharField(max_length = 100)

    def __str__(self) -> str:
        return self.nome
    
    @classmethod
    def get_(cls, _local:str):

        return cls.objects.filter(nome = _local)





class Movimentacao_financeiro(models.Model):

    class Meta:

        verbose_name = 'Movimentação das finanças'

        verbose_name_plural = 'Movimentações das finanças'

        ordering = ['data', 'categoria', 'status']

    nome = models.CharField(max_length = 100)

    data = models.DateField()

    valor = models.FloatField()

    categoria = models.ForeignKey(
        Categoria,
        on_delete = models.SET_NULL,
        blank = True,
        null = True
    )

    mes = models.IntegerField()

    movimentacao = models.BooleanField()

    status = models.BooleanField()

    local = models.ForeignKey(
        Locais,
        on_delete = models.SET_NULL,
        blank = True,
        null = True
    )

    def cofinho(self):

        self.mes = self.data.month

        if self.movimentacao:

            Financeiro.objects.get(pk = 0).deposito_cofrinho(self.valor)

        else:

            Financeiro.objects.get(pk = 0).saque_cofrinho(self.valor)

        self.save()

    def saldo(self):

        self.mes = self.data.month

        if self.movimentacao:

            Financeiro.objects.get(pk = 0).deposito_saldo(self.valor)

        else:

            Financeiro.objects.get(pk = 0).saque_saldo(self.valor)

        self.save()

    @classmethod
    def get_movimentacao_apagar(cls, _mes:int):

        return cls.objects.filter(
            mes = _mes
        )

financas/views/home.py
from django.shortcuts import render
from ..models import *

def dashboad(request):

    data = datetime.now().strftime("%d/%m/%Y")
    mes = datetime.now().month

    return render(
        request,
        'financas/paginas/index.html',
        {
            'titulo'        : 'Finanças',
            'dia'           : data,
            'movimentation' : Movimentacao_financeiro.get_movimentacao_apagar(mes),
            'financeiro'    : Financeiro.objects.get(pk = 1),
        }
    )

financas/templates/financas/paginas/index.html
{% extends "global/base.html" %}

{% block titulo_pagina %}
    <div class="cabecalho_pagina">
        <h4>{{ titulo }}</h4>
        <h6>{{ dia }}</h6>
    </div>
{% endblock titulo_pagina %}

{% block corpo_pagina %}
    <div class = "corpo_secundario">
        <div class = "card text-center">
            <div class = "card-header">
                <ul class = "nav nav-pills card-header-pills">
                    <li class = "nav-item">
                        <a style = "color: #f1f1f1 !important;" class = "nav-link action" aria-current = "true" href = "{% url "financeiro:dashboad" %}">Finanças</a>
                    </li>
                    <li class="nav-item">
                       <a style = "color: #323232 !important;" class = "nav-link" href = "{% url "financeiro:dashboad" %}">Cofrinho</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class = "card">
            <div class = "card-header">
                <h3>R$ {{ financeiro.saldo }}</h3>
                <h3>R$ {{ financeiro.cofrinho }}</h3>
            </div>
        </div>
        <div class = "responsive-table">
            <table class = "tarefas-table">
                <h3 class = "table-caption">
                    Teste
                </h3>
                <thead>
                    <tr class = "table-row table-row-header">
                        <th class = "table-header">Nome</th>
                        <th class = "table-header">Data</th>
                        <th class = "table-header">Categoria</th>
                        <th class = "table-header">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tarefa in tarefas %}
                        <tr class="table-row" onclick="window.location='{% url "agenda:descricao" tarefa.pk %}'" style="cursor: pointer;">
                            <td class="table-campo">
                                <p></p>
                            </td>
                            <td class="table-campo">
                                <p></p>
                            </td>
                            <td class="table-campo">
                                <p></p>
                            </td>
                            <td class="table-campo">
                                <p></p>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "parciais/_paginacao.html" %}
    </div>
{% endblock corpo_pagina %}