agenda/urls.py
from django.contrib import admin
from django.urls import path
from agenda.views import *

app_name = 'agenda'

urlpatterns = [
    path('tarefa/cadastro/', cadastro_tarefa, name = 'cadastro-tarefa'),
    path('tarefa/<int:id_tarefa>/alteracao/', alteracao_tarefa, name = 'alteracao-tarefa'),
    path('categoria/cadastro/', cadastro_categoria, name = 'cadastro-categoria'),
    path('tag/cadastro/', cadastro_tag, name = 'cadastro-tag'),
    path('cadastro/<int:id_tarefa>/descricao/', cadastro_descricao, name = 'cadastro-descricao'),
    path('cadastro/descricao/', cadastro_descricao, name = 'cadastro-descricao-form'),
    path('tarefa/<int:id_tarefa>/descricao/', descricao_tarefa, name = 'descricao'),
    path('tarefa/<int:id_tarefa>/deletar/', remover_tarefa, name = 'deletar'), # type: ignore
    path('tarefa/<int:id_tarefa>/concluida/', concluir_tarefa, name = 'concluir-tarefa'), # type: ignore
    path('ciclo/<int:id_ciclo>/descricao/', descricao_ciclo, name = 'descricao-ciclo'),
    path('ciclo/', home_ciclo, name = 'home-ciclo'),
    path('', home, name = 'home'),
]

project/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('financas/', include('financas.urls')),
    path('', include('agenda.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agenda/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Categoria(models.Model):

    class Meta:

        verbose_name = 'Categoria'

        verbose_name_plural = 'Categorias'

    nome = models.CharField(max_length = 100)

    def __str__(self) -> str:
        return self.nome


class Tarefa(models.Model):
    
    class Meta:

        verbose_name = 'Tarefa'
    
        verbose_name_plural = 'Tarefas'

        ordering = ['data', 'categoria', 'visibilidade']

    nome = models.CharField(max_length = 100)

    data = models.DateField(default = timezone.now().date())

    mes = models.IntegerField(default = 0)

    hora = models.TimeField(default = timezone.now().time())

    categoria = models.ForeignKey(
        Categoria,
        on_delete = models.SET_NULL,
        blank = True,
        null = True
    )

    visibilidade = models.BooleanField(default = True)

    status = models.BooleanField(default = False)

    @classmethod
    def atividades_do_mes(cls, _mes:int, visi:bool = True):
        
        return cls.objects.filter(
            visibilidade=visi,
            mes=_mes
        ).order_by('data', 'categoria')
    
    @classmethod
    def get_tarefa_categoria(cls, id_tarefa, visi:bool = True):

        return cls.objects.filter(
            visibilidade = visi,
            pk = id_tarefa
        ).order_by('categoria')
    
    
    def deletar_tarefa(self):

        self.visibilidade = False


class Conjunto_tarefa(models.Model):

    class Meta:

        verbose_name = 'Conjunto'

        verbose_name_plural = 'Conjuntos'

    nome = models.CharField(max_length = 100)

    id_tarefa = models.IntegerField()

    def __str__(self) -> str:
        
        return self.nome
    
    @classmethod
    def adicionar_tarefa(cls, id_tar:int, nome_conjunto:str):

        nova = cls(nome = nome_conjunto, id_tarefa = id_tar)

        nova.save()


class Tag(models.Model):

    class Meta:

        verbose_name = 'Tag'

        verbose_name_plural = 'Tags'

    nome = models.CharField(max_length = 100)

    cor = models.CharField(max_length = 20)

    def __str__(self) -> str:
        return self.nome


class Descricao(models.Model):

    class Meta:

        verbose_name = 'Descrição'

        verbose_name_plural = 'Descrições'

        ordering = ['tag__nome', 'tag__cor']

    assunto = models.TextField()

    tag = models.ForeignKey(
        Tag,
        on_delete = models.SET_NULL,
        blank = True,
        null = True
    )

    tarefa = models.IntegerField()

    def __str__(self) -> str:
        return self.tag.nome # type: ignore
    
    @classmethod
    def get_descricoes(cls, id_tarefa:int):
        
        return cls.objects.filter(
            tarefa = id_tarefa
        )


class Ciclo(models.Model):

    class Meta:

        verbose_name = 'Ciclo'

        verbose_name_plural = 'Ciclos'

    nome = models.CharField(max_length = 100)

    descricao = models.TextField(default = "")

    tempo_disponivel_semana = models.IntegerField(default = 1)

    def __str__(self) -> str:
        
        return self.nome
    
    @classmethod
    def reiniciar_ciclo(cls, id_ciclo:int):

        elementos = Elemento_ciclo.objects.all().filter(ciclo = id_ciclo)

        for elem in elementos:

            elem.horas_cumpridas = 0

            elem.save()


class Elemento_ciclo(models.Model):

    class Meta:

        verbose_name = 'Elemento de ciclo'

        verbose_name_plural = 'Elementos de clico'

        ordering = ['categoria__nome', 'ciclo__pk']

    horas_categoria = models.IntegerField(default = 0)

    horas_cumpridas = models.IntegerField(default = 0)

    categoria = models.ForeignKey(
        Categoria,
        on_delete = models.SET_NULL,
        blank = True,
        null = True
    )

    dificuldade = models.IntegerField(default = 1)

    ciclo = models.ForeignKey(
        Ciclo,
        on_delete = models.SET_NULL,
        blank = True,
        null = True
    )

    @classmethod
    def get_categoria(cls, id_ciclo:int):

        return cls.objects.filter(
            ciclo = id_ciclo
        )

agenda/forms/forms__crud.py
from bootstrap_datepicker_plus import widgets
from django.forms import ChoiceField, ModelForm
from agenda.models import *
from django import forms

class Categoria_form(ModelForm):

    class Meta:

        model = Categoria

        fields = (
            'nome',
        )

        widgets = {
            'nome' : forms.TextInput(
                attrs = {
                    'class' : 'texto form-control',
                    'placeholder' : 'Digite o nome da categoria',
                }
            )
        }

class Tarefa_form(ModelForm):

    class Meta:
    
        model = Tarefa
    
        fields = (
            'nome',
            'data',
            'categoria',
            'mes',
        )

        widgets = {
            'nome' : forms.TextInput(
                attrs = {
                    'class'       : 'texto form-control',
                    'placeholder' : 'Digite o nome da categoria',
                }
            ),
            'data': forms.DateInput(
                attrs = {
                    'class' : 'texto form-control',
                },
                format = "%d/%m/%Y",
            ),
            'categoria' : forms.Select(
                attrs = {
                    'class' : 'texto form-select',
                },
            ),
            'mes' : forms.NumberInput(
                attrs = {
                    'class' : 'texto form-control', 
                }
            ),
        }

class Tag_form(ModelForm):

    class Meta:

        model = Tag

        fields = (
            'nome',
            'cor'
        )

class Descricao_form(ModelForm):

    class Meta:

        model = Descricao

        fields = (
            'assunto',
            'tag',
        )

class Ciclo_form(ModelForm):

    class Meta:

        model = Ciclo

        fields = (
            'nome',
            'tempo_disponivel_semana',
        )

        widgets = {
            'nome' : forms.TextInput(
                attrs = {
                    'class'       : 'texto form-control',
                    'placeholder' : 'Digite o nome da categoria',
                }
            ),
            'tempo_disponivel_semana' : forms.NumberInput(
                attrs = {
                    'class' : 'texto form-control',
                    'placeholder' : 'Digite a quantidade de horas disponivel na sua semana.',
                }
            )
        }


class Elemento_ciclo_form(ModelForm):

    class Meta:

        model = Elemento_ciclo

        fields = (
            'horas_categoria',
            'categoria',
            'dificuldade',
        )

        widgets = {
            'horas_categoria' : forms.NumberInput(
                attrs = {
                    'class'       : 'form-control',
                }
            ),
            'categoria' : forms.Select(
                attrs = {
                    'class' : 'form-select',
                },
            ),
            'dificuldade' : forms.NumberInput(
                attrs = {
                    'class'       : 'form-control',
                }
            ),
        }

agenda/views/_ciclo.py
from django.shortcuts import render, redirect, get_object_or_404
from project.constantes_app import *
from django.urls import reverse
from datetime import datetime
from agenda.models import *
from agenda.forms import *
import locale


locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')

def home_ciclo(request):

    dia_hoje = datetime.now().strftime("%d/%m/%Y")

    ciclos = Ciclo.objects.all().filter()

    context = {
        'titulo'   : 'Ciclo de estudo',
        'dia_hoje' : f'{dia_hoje[0].upper() + dia_hoje[1:]}',
        'ciclos'   : ciclos,
    }

    return render(
        request,
        'agenda/paginas/ciclo/home_ciclo.html',
        context
    )

def descricao_ciclo(request, id_ciclo:int):

    dia_hoje = datetime.now().strftime("%d/%m/%Y")

    ciclo = get_object_or_404(
        Ciclo,
        pk = id_ciclo
    )

    categorias = Elemento_ciclo.get_categoria(id_ciclo)

    context = {
        'titulo'   : 'Ciclo ' + ciclo.nome,
        'dia_hoje' : f'{dia_hoje[0].upper() + dia_hoje[1:]}',
        'categorias' : categorias,
        'ciclo'    : ciclo,
    }

    return render(
        request,
        'agenda/paginas/ciclo/descricao_ciclo.html',
        context
    )

agenda/views/_crud.py
from django.shortcuts import render, redirect, get_object_or_404
from project.constantes_app import *
from django.urls import reverse
from datetime import datetime
from agenda.models import *
from agenda.forms import *
import locale


locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')

def cadastro_tarefa(request):

    form_action = reverse('agenda:cadastro-tarefa')
    
    categorias = Categoria.objects.all().filter()

    if request.method == 'POST':

        print(11)
    
        form = Tarefa_form(request.POST)
    
        context = {
            'titulo'       : 'Cadastro de tarefa',
            'categorias'   : categorias,
            'form'         : form,
            'pagina'       : 'tarefa',
            'form_action'  : form_action,
        }

        print(form.is_valid())

        if form.is_valid():

            print(22)
    
            nova_tarefa = form.save(commit = False)
    
            nova_tarefa.save()
    
            return redirect('agenda:descricao', nova_tarefa.pk)
        
        return render(
    
            request,
            'agenda/paginas/tarefa_form.html',
            context = context
        )
    
    context = {    
        'titulo'       : 'Cadastro de tarefa',
        'categorias'   : categorias,
        'pagina'       : 'tarefa',
        'form'         : Tarefa_form(),
    }

    return render(
        request,
        'agenda/paginas/tarefa_form.html',
        context = context
    )

def cadastro_categoria(request):

    form_action = reverse('agenda:cadastro-categoria')

    if request.method == 'POST':
    
        form = Categoria_form(request.POST)
    
        context = {
            'titulo'       : 'Cadastro de categoria',
            'form'         : form,
            'pagina'       : 'categoria',
            'form_action'  : form_action,
        }

        if form.is_valid():
    
            nova_categoria = form.save(commit = False)
    
            nova_categoria.save()
    
            return redirect('agenda:cadastro-tarefa')
        
        return render(
    
            request,
            'agenda/paginas/tarefa_form.html',
            context = context
        )
    
    context = {    
        'titulo'       : 'Cadastro de categoria',
        'pagina'       : 'categoria',
        'form'         : Categoria_form(),
    }

    return render(
        request,
        'agenda/paginas/tarefa_form.html',
        context = context
    )

def cadastro_tag(request):

    form_action = reverse('agenda:cadastro-tag')

    if request.method == 'POST':
    
        form = Tag_form(request.POST)
    
        context = {
            'titulo'       : 'Cadastro de tag',
            'form'         : form,
            'pagina'       : 'tag',
            'form_action'  : form_action,
        }

        if form.is_valid():
    
            nova_tag = form.save(commit = False)
    
            nova_tag.save()
    
            return redirect('agenda:cadastro-categoria')
        
        return render(
    
            request,
            'agenda/paginas/tarefa_form.html',
            context = context
        )
    
    context = {    
        'titulo'       : 'Cadastro de tag',
        'pagina'       : 'tag',
        'form'         : Tag_form(),
    }

    return render(
        request,
        'agenda/paginas/tarefa_form.html',
        context = context
    )

def cadastro_descricao(request, id_tarefa:int):

    form_action = reverse('agenda:cadastro-descricao-form')

    if request.method == 'POST':
    
        form = Descricao_form(request.POST)
    
        context = {
            'titulo'       : 'Cadastro de descrição',
            'form'         : form,
            'pagina'       : 'descricao',
            'form_action'  : form_action,
        }

        if form.is_valid():
    
            nova_descricao = form.save(commit = False)

            nova_descricao.tarefa = id_tarefa
    
            nova_descricao.save()
    
            return redirect('agenda:descricao', id_tarefa=id_tarefa)
        
        return render(
    
            request,
            'agenda/paginas/tarefa_form.html',
            context = context
        )
    
    context = {    
        'titulo'       : 'Cadastro de descrição',
        'pagina'       : 'descricao',
        'form'         : Descricao_form(),
    }

    return render(
        request,
        'agenda/paginas/tarefa_form.html',
        context = context
    )

def remover_tarefa(request, id_tarefa:int):

    tarefa = get_object_or_404(
        Tarefa.objects.filter(
            pk = id_tarefa,
            visibilidade = True
        ),
    )

    tarefa.deletar_tarefa()

    tarefa.save()

    return redirect('agenda:home')

def concluir_tarefa(request, id_tarefa:int):

    tarefa = get_object_or_404(
        Tarefa.objects.filter(
            pk = id_tarefa
        ),
    )

    tarefa.status = True

    tarefa.save()

    return redirect('agenda:descricao', id_tarefa)

def alteracao_tarefa(request, id_tarefa:int):

    tarefa = get_object_or_404(
        Tarefa,
        pk = id_tarefa,
        visibilidade = True
    )
    
    form_action = reverse('agenda:alteracao-tarefa', args = (id_tarefa, ))
    
    categorias = Categoria.objects.all().filter()

    if request.method == 'POST':
    
        form = Tarefa_form(request.POST, instance = tarefa)
    
        context = {
            'titulo'       : 'Alteracao de tarefa',
            'categorias'   : categorias,
            'form'         : form,
            'pagina'       : 'alteracao',
            'form_action'  : form_action,
        }

        if form.is_valid():
    
            nova_tarefa = form.save(commit = False)
    
            nova_tarefa.save()
    
            return redirect('agenda:descricao', nova_tarefa.pk)
        
        return render(
    
            request,
            'agenda/paginas/tarefa_form.html',
            context = context
        )
    
    context = {    
        'titulo'       : 'Alteração de tarefa',
        'categorias'   : categorias,
        'pagina'       : 'alteracao',
        'form'         : Tarefa_form(instance = tarefa),
    }

    return render(
        request,
        'agenda/paginas/tarefa_form.html',
        context = context
    )

agenda/views/home.py
from django.shortcuts import render, get_object_or_404
from project.constantes_app import *
from datetime import datetime
from agenda.models import *
import locale


locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')

def home(request):
    dia_hoje = datetime.now().strftime("%d/%m/%Y")

    tarefas = Tarefa.atividades_do_mes(int(datetime.now().strftime("%m")))

    context = {
        'titulo'   : 'Agenda mensal',
        'pagina'   : 'mensal',
        'dia_hoje' : f'{dia_hoje[0].upper() + dia_hoje[1:]}',
        'tarefas'  : paginacao_geral(request, tarefas, 20),
    }

    return render(
        request,
        'agenda/paginas/index.html',
        context
    )

def descricao_tarefa(request, id_tarefa:int):

    tarefa = get_object_or_404(
        Tarefa.objects.filter(
            pk = id_tarefa,
            visibilidade = True
        ),
    )

    lembretes = Descricao.objects.all().filter(tarefa = id_tarefa)

    context = {
        'titulo'    : f'Descricao da tarefa {tarefa.nome}',
        'tarefa'    : tarefa,
        'lembretes' : lembretes,
    }

    return render(
        request,
        'agenda/paginas/tarefa.html',
        context
    )

agenda/templates/agenda/paginas/index.html
{% extends "global/base.html" %}

{% block titulo_pagina %}
    <div class="cabecalho_pagina">
        <h4>{{ titulo }}</h4>
        <h6>{{ dia_hoje }}</h6>
    </div>
{% endblock titulo_pagina %}

{% block corpo_pagina %}
    <div class = "corpo_secundario">
        <div class = "card text-center">
            <div class = "card-header">
                <ul class = "nav nav-pills card-header-pills">
                    <li class = "nav-item">
                        {% if pagina == 'mensal' %}
                            <a class = "nav-link-principal action" aria-current = "true" href = "{% url "agenda:cadastro-tarefa" %}">Agenda mensal</a>
                        {% else %}
                            <a style = "color: var(--preto) !important;" class = "nav-link" href = "{% url "agenda:cadastro-tarefa" %}">Agenda mensal</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if pagina == 'semanal' %}
                            <a class = "nav-link action" aria-current = "true" href = "{% url "agenda:cadastro-categoria" %}">Agenda semanal</a>
                        {% else %}
                            <a style = "color: var(--preto) !important;" class = "nav-link" href = "{% url "agenda:cadastro-categoria" %}">Agenda semanal</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <div class = "card-header">
                <ul class = "nav nav-pills card-header-pills">
                    <li class = "nav-item">
                        <a class = "nav-link" href = "{% url "agenda:cadastro-tarefa" %}">Cadastro de tarefa</a>
                    </li>
                    
                </ul>
            </div>
        </div>
        <div class = "responsive-table">
            <table class = "tarefas-table">
                <h3 class = "table-caption">
                    Tarefas do mês
                </h3>
                <thead>
                    <tr class = "table-row table-row-header">
                        <th class = "table-header">Nome</th>
                        <th class = "table-header">Data</th>
                        <th class = "table-header">Categoria</th>
                        <th class = "table-header">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tarefa in tarefas %}
                        <tr class="table-row" onclick="window.location='{% url "agenda:descricao" tarefa.pk %}'" style="cursor: pointer;">
                            <td class="table-campo">
                                <p>{{ tarefa.nome }}</p>
                            </td>
                            <td class="table-campo">
                                <p>{{ tarefa.data }}</p>
                            </td>
                            <td class="table-campo">
                                <p>{{ tarefa.categoria }}</p>
                            </td>
                            <td class="table-campo">
                                {% if tarefa.status == True %}
                                <p class = "texto-verde">Concluida</p>
                                {% else %}
                                    <p class = "texto-vermelho">Não concluida</p>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "parciais/_paginacao.html" %}
    </div>
{% endblock corpo_pagina %}

agenda/templates/agenda/paginas/tarefa.html
{% extends "global/base.html" %}


{% block titulo_pagina %}
<div class="cabecalho_pagina">
    <h4>{{ titulo }}</h4>
</div>
{% endblock titulo_pagina %}

{% block corpo_pagina %}

<div class = "corpo_secundario">
    <div class = "menu-lateral">
        <h2 style="margin-left: 15px"><i class="bi bi-map"></i> Guia</h2>
        <br>
        <ol class="list-group list-group-numbered elementos-descricao">
            <a href = "{% url "agenda:cadastro-descricao" tarefa.pk %}"><i class="bi bi-caret-right-fill"></i>Adicionar descrição</a>
            <a href = "{% url "agenda:alteracao-tarefa" tarefa.pk %}"><i class="bi bi-caret-right-fill"></i>Alterar tarefa</a>
            <a href = "{% url "agenda:concluir-tarefa" tarefa.pk %}"><i class="bi bi-caret-right-fill"></i>Concluir tarefa</a>
            <a href = "{% url "agenda:deletar" tarefa.pk %}"><i class="bi bi-caret-right-fill"></i>Deletar tarefa</a>
        </ol>
    </div>
    <br>
    <div class = "corpo-tarefa">
        <h3 class = "titulo-corpo">Titulo: {{ tarefa.nome }}</h3>
        <h5 class = "elemento-corpo">Data: {{ tarefa.data }}</h5>
        <h5 class = "elemento-corpo">Categoria: {{ tarefa.categoria }}</h5>
        {% if tarefa.status == True %}
            <h5 style = "color: #126d3b !important; font-weight: bold;" class="elemento-corpo">Status: Tarefa concluida.</h5>
        {% else %}
            <h5 style = "color: #A72F1D !important; font-weight: bold;" class="elemento-corpo">Status: Tarefa não concluida.</h5>
        {% endif %}
        <br>
        <div class="quadro-descricao">
            <h4 class = "elemento-corpo">Lembretes da tarefa:</h4>
            {% for lembrete in lembretes %}
                <h5 style = "color: {{ lembrete.tag.cor }} !important;" class = "elemento-corpo">{{ lembrete.tag.nome }}: {{ lembrete.assunto }}<h5>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock corpo_pagina %}

agenda/templates/agenda/paginas/tarefa_form.html
{% extends "global/base.html" %}

{% block titulo_pagina %}
    <div class = "cabecalho_pagina">
        <h4>{{ titulo }}</h4>
    </div>
{% endblock titulo_pagina %}

{% block corpo_pagina %}
    <div class = "corpo_secundario">
            <div class = "texto-titulo">
                <h1>{{ titulo }}</h1>
            </div>
            {% if pagina != 'descricao' %}
                <div class = "card text-center">
                    <div class = "card-header">
                        <ul class = "nav nav-pills card-header-pills">
                            <li class = "nav-item">
                                {% if pagina == 'tarefa' %}
                                    <a class = "nav-link action" aria-current = "true" href = "{% url "agenda:cadastro-tarefa" %}">Tarefa</a>
                                {% else %}
                                    <a style = "color: var(--preto) !important;" class = "nav-link" href = "{% url "agenda:cadastro-tarefa" %}">Tarefa</a>
                                {% endif %}
                            </li>
                            <li class="nav-item">
                                {% if pagina == 'categoria' %}
                                    <a class = "nav-link action" aria-current = "true" href = "{% url "agenda:cadastro-categoria" %}">Categoria</a>
                                {% else %}
                                    <a style = "color: var(--preto) !important;" class = "nav-link" href = "{% url "agenda:cadastro-categoria" %}">Categoria</a>
                                {% endif %}
                            </li>
                            <li class="nav-item">
                                {% if pagina == 'tag' %}
                                    <a class = "nav-link action" aria-current = "true" href = "{% url "agenda:cadastro-tag" %}">Tag</a>
                                {% else %}
                                    <a style = "color: var(--preto) !important;" class="nav-link" href = "{% url "agenda:cadastro-tag" %}">Tag</a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
            {% endif %}
            <div class = "card-body">
                {% include "parciais/_form.html" %}
            </div>    
        </div>
    </div>
{% endblock corpo_pagina %}